//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloonTowerMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloonTowerMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap army {
            get {
                object obj = ResourceManager.GetObject("army", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string EmptyPropertyValue {
            get {
                return ResourceManager.GetString("EmptyPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImageIcon {
            get {
                return ResourceManager.GetString("ImageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImagePortrait {
            get {
                return ResourceManager.GetString("ImagePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magic {
            get {
                object obj = ResourceManager.GetObject("magic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn_t.
        /// </summary>
        internal static string PathButtonIndentifier {
            get {
                return ResourceManager.GetString("PathButtonIndentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap primary {
            get {
                object obj = ResourceManager.GetObject("primary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectiles.
        /// </summary>
        internal static string ProjectileFolder {
            get {
                return ResourceManager.GetString("ProjectileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectiles.json.
        /// </summary>
        internal static string ProjectileJson {
            get {
                return ResourceManager.GetString("ProjectileJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weapons.
        /// </summary>
        internal static string ProjectileWeaponFolder {
            get {
                return ResourceManager.GetString("ProjectileWeaponFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.json.
        /// </summary>
        internal static string ProjectMainFile {
            get {
                return ResourceManager.GetString("ProjectMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources.
        /// </summary>
        internal static string ProjectResourcesFolder {
            get {
                return ResourceManager.GetString("ProjectResourcesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap support {
            get {
                object obj = ResourceManager.GetObject("support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attack.json.
        /// </summary>
        internal static string TowerAttackJsonFile {
            get {
                return ResourceManager.GetString("TowerAttackJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.json.
        /// </summary>
        internal static string TowerGlobalAttackJsonFile {
            get {
                return ResourceManager.GetString("TowerGlobalAttackJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damage.json.
        /// </summary>
        internal static string TowerGlobalDamageJsonFile {
            get {
                return ResourceManager.GetString("TowerGlobalDamageJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tower.json.
        /// </summary>
        internal static string TowerModelJsonFile {
            get {
                return ResourceManager.GetString("TowerModelJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.json.
        /// </summary>
        internal static string TowerPathJsonFile {
            get {
                return ResourceManager.GetString("TowerPathJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textures.json.
        /// </summary>
        internal static string TowerTexturesJsonFile {
            get {
                return ResourceManager.GetString("TowerTexturesJsonFile", resourceCulture);
            }
        }
    }
}
